### ISSUE TITLE
[Server] ValidationPipe transform does not work

### ISSUE THREAD

**Issue by min112402** [wafflestudio/snuboard-server#13]
[문제상황]

parameter로 받은 string을 DTO에 명시된 타입으로 자동으로 변환해주는 transform 기능이 작동하지 않습니다.

user api의 DTO에 명시된 타입이 우연히도(!!) 모두 string이라서 지금까지 transform없이도 오류가 나지 않은 것으로 보입니다. 

[해결방법]

https://github.com/wafflestudio/snuboard-server/blob/2d47b8a35260a2a6b05d861acdb75bc229e6d222/src/main.ts#L10-L14

ValidationPipeOption에 ` transformOptions: {enableImplicitConversion: true},`를 추가하면 의도대로 작동합니다. 

참고: 
https://github.com/nestjs/nest/issues/5253
https://stackoverflow.com/questions/58377492/query-does-not-transform-to-dto

여러 문서를 보면 enableImplicitConversion을 세팅하지 않아도 transform을 true로 설정하는 것만으로 transform이 되는 것이 일반적인 것 같은데 왜 우리 프로젝트에서는 안되는지는 의문입니다...
일단 이대로 세팅하고 사용하면 될 것 같습니다.

**Comment by eldpswp99** [comment]
@min112402 어떠한 param을 변환하고자 하시는지 말씀해주실수 있을까요?
![image](https://user-images.githubusercontent.com/58476210/107806775-9d8c0800-6daa-11eb-8d05-3fa69236856a.png)
에서는 class-validator을 사용하면 웬만하면 사용 안하게 될 것이라고 해서 안쓰고 해결할 수 있으면 좋을 듯 해서요
저는 path param같은 경우는 지금 validator이용해서 number로 변환해서 사용하고 있습니다

**Comment by min112402** [comment]
query로 받는 parameter들을 dto를 이용해서 한번에 변환해서 사용하려고 했었습니다. query param은 기본적으로 string으로 들어와서 변환이 필요하고 인자가 많다보니 가능하면 dto와 ValidationPipe를 활용해보려고 시도하다가 찾은 방법입니다. 지금 보니 저렇게 세팅하면  body같은 경우에는 문제가 생길 수 있겠네요.. 

method 범위에서만 옵션을 주거나  변환하는 다른 방법을 찾아서 해결해보도록 하겠습니다.

**Comment by eldpswp99** [comment]
네넵 제가 올린 사진에서처럼 method안에서 plainToClass와 같이 변환해서 사용하면 괜찮을 것 같습니다!
