### ISSUE TITLE
Notice Entity의 content 글자 수 제한

### ISSUE THREAD

**Issue by gyusang** [wafflestudio/snuboard-server#21]
https://github.com/wafflestudio/snuboard-server/blob/359b7decf6fb970576e4ed001c6d79676ddca688/src/notice/notice.entity.ts#L24-L25
에서 notice content가 10000자로 제한되어 있습니다.
글마다 글자수가 천차만별인 만큼, 글자수 제한이 보다 큰 형태로 변경하는 것이 어떨까요?
크롤링을 해보니 지금의 글자수로는 부족합니다.

**Comment by eldpswp99** [comment]
네네 이 이후에도 부족하면 더 큰 자료형을 쓰는 방식으로 가면 될 듯 합니다
