### ISSUE TITLE
Slow query (Search API)

### ISSUE THREAD

**Issue by jusjinuk** [wafflestudio/snuboard-server#64]
#55, #56 과 비슷한 문제인 듯 합니다.
특정 과들에서 `GET notices/department/{id}/search/?keywords={keyword}&limit=10&content=true&title=true&tags=`의 response가 오는 데 굉장히 오래걸리는 것을 확인했습니다.
아래의 예시는 산업공학과입니다. 9초가 넘는 시간이 소요됩니다.

```
I/okhttp.OkHttpClient: --> GET https://snuboard-api.wafflestudio.com/notices/department/8/search/?keywords=cse&limit=10&content=true&title=true&tags=
    Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMSIsImlkIjoxLCJpYXQiOjE2MjUyODI3MjYsImV4cCI6MTYyNTMxODcyNn0.ur_6cohfV-iWpbxceNnMeRTK-IFXNHgG6QmAKaKCn60
    --> END GET
I/okhttp.OkHttpClient: <-- 200 https://snuboard-api.wafflestudio.com/notices/department/8/search/?keywords=cse&limit=10&content=true&title=true&tags= (9781ms)
    date: Sat, 03 Jul 2021 10:40:42 GMT
    content-type: application/json; charset=utf-8
    content-length: 4008
    server: nginx
    apigw-requestid: B465GgWZoE0EJ3Q=
```

**Comment by eldpswp99** [comment]
@min112402 이 부분은 저번에 상민님이 말씀하셨던 search query 성능 향상 방법 사용하면 될 것 같은데요. 어떻게 생각하시나요?

**Comment by min112402** [comment]
> @min112402 이 부분은 저번에 상민님이 말씀하셨던 search query 성능 향상 방법 사용하면 될 것 같은데요. 어떻게 생각하시나요?

검색을 하려면 contentText를 한번 스캔하는 것을 피할 수 없을 것 같네요. 
저번에 얘기했던 full-text search는 오버헤드가 커서(indexing으로 용량 차지, db설정 변경 및 재시작 필요) 일단 다른 방법부터 시도해보려고 합니다.

**Comment by eldpswp99** [comment]
좋은 방법이 없다면 제목 한정으로 search를 구현해도좋을거같습니다

**Comment by min112402** [comment]
> 좋은 방법이 없다면 제목 한정으로 search를 구현해도좋을거같습니다

제목에서만 검색을 하면 검색 기능의 유용성이 많이 줄어들 것 같습니다. 희박하게 등장하는 단어가 아니면 속도가 괜찮게 나오는 것 같아서 본문 검색을 계속 유지했으면 합니다. 

다른 방법도 생각해봤지만 검색 기능을 충실하게 구현하면서 속도도 확보하려면 full text search가 최선인 것 같습니다..
