### ISSUE TITLE
Typescript compile error

### ISSUE THREAD

**Issue by gyusang** [wafflestudio/snuboard-server#9]
크롤러 프로젝트에서 Entity를 컴파일하던 중 다음 줄에서
https://github.com/wafflestudio/snuboard-server/blob/2d47b8a35260a2a6b05d861acdb75bc229e6d222/src/department/department.entity.ts#L16
`Error:(16, 3) TS2564: Property 'id' has no initializer and is not definitely assigned in the constructor.`
이 발생함을 확인했습니다.

https://github.com/Microsoft/TypeScript-Vue-Starter/issues/36
이 내용을 참고해 `:`을 `!:`으로 변경했더니 컴파일이 정상적으로 진행됐습니다.
이렇게 수정해야 할까요?

**Comment by gyusang** [comment]
제가 `tsconfig.json`에 `"strict": true`를 설정해 두어서 에러가 보이는 것 같습니다.
https://github.com/wafflestudio/snuboard-server/blob/2d47b8a35260a2a6b05d861acdb75bc229e6d222/src/user/user.entity.ts#L71
에서 `'User | undefined` Type을 `User`에 assign할 수 없다는 에러가 발생하고,
77, 81줄에서도 비슷한 에러가 발생합니다.

**Comment by eldpswp99** [comment]
넵 내일 확인후에 수정하도록 하겠습니다!
